### ISSUE TITLE
Problem with ESP8266 Core 2.4.0

### ISSUE THREAD

**Issue by Refenz** [blynkkk/blynk-library#384] opened 2018-01-04 17:31 UTC
Blynk library version: [0.5.0 / 0.4.10]
IDE: [Arduino]
IDE version: [1.8.4]
Board type: [NodeMCU / SF Blynk Board]

### Scenario, steps to reproduce
Use last ESP8266 Core(2.4.0).
Open the sketch for Dynamic Provisioning.
Upload the sketch to the board.
Run and go through Dynamic Provisioning.

### Expected Result
Successful connection of the board to the project. 
Reboot the board does not take place.

### Actual Result
```
[85219] WAIT_CONFIG => CONFIGURING
[88479] WiFi SSID: Dom2 Pass: 29727261
[88479] Blynk cloud: 1df953dbf7ec40a798bd78c63dc74f9b @ iotics.blynk.cc:8442
[88481] CONFIGURING => SWITCH_TO_STA
[88482] Switching to STA...
[89943] SWITCH_TO_STA => CONNECTING_NET
[89945] Connecting to WiFi: Dom2

Exception (0):
epc1=0xc845a2ce epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffba0 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffd40:  00000090 3fff1a34 3fff1f8c 401043d1  
3ffffd50:  3fff34cc 3ffeec68 00000000 00000030  
3ffffd60:  0000003c 00000000 401030c9 3fff1a69  
3ffffd70:  3fff1a34 3fff1a34 3fff34cc 4010453d  
3ffffd80:  40214377 3fff34cc 3fff3502 40214380  
3ffffd90:  00000008 3fff189c 00000000 3ffee590  
3ffffda0:  40103e13 3ffee920 3fff1a34 3fff18a0  
3ffffdb0:  3fff1a69 00000000 3fff1a34 4021a19c  
3ffffdc0:  3fffc278 40101f8c 3fffc200 00000022  
3ffffdd0:  00000000 3fff34cc 3ffee078 00000016  
3ffffde0:  4023fc16 00000030 0000000f 3fff3510  
3ffffdf0:  3fff34cc 3fff2c88 3fff1a34 4021a3f4  
3ffffe00:  40210000 3fff3e7c 3ffeb722 3ffeefc0  
3ffffe10:  00000014 3fff2c88 3fff34cc 4021ada0  
3ffffe20:  3ffeed38 3ffeec68 3ffef3b8 00000018  
3ffffe30:  3fff2c84 000000ff 00000000 00000006  
3ffffe40:  3fff198c 3ffffed0 3ffffed0 00000001  
3ffffe50:  326d6f44 0574da00 401021f2 3fff1a34  
3ffffe60:  3fff2c84 3fff2e34 00000000 4021ade0  
3ffffe70:  3fff1a34 00000000 00000000 3fff21b4  
3ffffe80:  ffffffd7 3ffeb6c0 ffffffd7 4021ae06  
3ffffe90:  3fff1a34 00000000 00000000 4021b4ff  
3ffffea0:  4000050c 3fff3e7c 3ffeb6c0 40218546  
3ffffeb0:  3fff1a34 00000030 00000011 ffffffff  
3ffffec0:  00000218 3fff2c88 3fff3524 3fff3524  
3ffffed0:  3ffef9f8 4021543c 3fff19ac 3fff2c84  
3ffffee0:  4021533c 00000000 3fff1a7c 40218889  
3ffffef0:  00000000 3fffdcb0 3ffefa48 402148f1  
3fffff00:  3fff04a8 0000029a 0000029a 4010020c  
3fffff10:  4021533c 3fff164c 3fff2fc4 3fff1648  
3fffff20:  4021533c 3fff164c 00000000 40214e34  
3fffff30:  4022c7dc 3ffee230 3fff3e7c 40215344  
3fffff40:  40223336 3ffee230 00000000 4021548c  
3fffff50:  00000000 00000000 00000001 4020cfb1  
3fffff60:  402338b4 3ffef9f8 3ffefa20 60000600  
3fffff70:  05753c93 3ffefa20 3ffef9f8 402338c1  
3fffff80:  40233906 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffefa30 3fffdad0 3fff05a8 4020cf4b  
3fffffa0:  40000f49 40000f49 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(1,6)


 ets Jan  8 2013,rst cause:4, boot mode:(1,6)

wdt reset

```
P.S. connection is successful if use ESP8266 Core (2.4.0-rc2)

**Comment by vshymanskyy** [comment] 2018-01-07 20:34
This is caused by another bug in the Core. Hopefully fixed with: https://github.com/esp8266/Arduino/pull/4105
Currently the workaround would be to select `Tools -> lwIP Variant -> v1.4 Prebuilt`.

**Comment by Refenz** [comment] 2018-01-09 00:57
@vshymanskyy 
The workaround works fine.

**Closed** 2018-05-14 14:07 UTC
Labels: bug, for reference
