### ISSUE TITLE
Compilation error for myPlant Demo

### ISSUE THREAD

**Issue by doom369** [blynkkk/blynk-library#203] opened 2016-09-29 22:26 UTC
```
In file included from sketch/BlynkProvisioning.h:16:0,
                 from /home/doom369/sketchbook/libraries/Blynk/examples/Export_Demo/myPlant_ESP8266/myPlant_ESP8266.ino:20:
sketch/Indicator.h:12:33: fatal error: Adafruit_NeoPixel.h: No such file or directory
   #include <Adafruit_NeoPixel.h>
                                 ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

**Comment by vshymanskyy** [comment] 2016-10-01 09:04
Just install NeoPixel library. Need to add to the doc.

**Comment by vshymanskyy** [comment] 2016-10-01 09:05
@blynkkk , maybe we can just include neopixel in our .zip ?

**Comment by doom369** [comment] 2016-10-01 09:21
@vshymanskyy do we really need it?

**Comment by vshymanskyy** [comment] 2016-10-01 09:22
Yes.

**Comment by doom369** [comment] 2016-10-01 09:24
Ok. Please update github doc accordingly - https://github.com/blynkkk/blynk-library/blob/master/examples/Export_Demo/myPlant_ESP8266/README.md.

**Comment by vshymanskyy** [comment] 2016-10-03 09:36
I will include Neopixel library in 0.3.10 zip release

**Comment by vshymanskyy** [comment] 2016-10-03 09:44
Duplicate of https://github.com/blynkkk/blynk-library/issues/205

**Closed by vshymanskyy** 2016-10-03 09:44 UTC
Labels: bug, HIGH PRIORITY
